name: Python CI on macOS
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Replace with your Python version (e.g., '3.9')
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run eye_tracker_for_mac.py
        run: python eye_tracker_for_mac.py